version: '3.3'

services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - type: bind
        source: ./mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
  nodered:
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - node_red_data:/data

volumes:
  node_red_data:
  mosquitto_data: