version: '3.5'

services:

  mosquitto:
    container_name: oneboard-mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - type: bind
        source: ./mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    networks:
      - oneboard-net

  nodered:
    container_name: oneboard-nodered
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - node_red_data:/data
    networks:
      - oneboard-net

  # oneboard-gateway:
  #   container_name: oneboard-gateway
  #   build:
  #     context: .
  #   image: oneboard-gateway
  #   environment: 
  #     - LOCAL_BROKER_URL=mqtt://mosquitto
  #     - REMOTE_BROKER_URL=mqtt://192.168.1.103
  #     - ARP_ROOT=http://192.168.1.103:3000/api/arp/
  #     - GATEWAY_SERIAL=gateway_k_seil
  #     - DOCKER_HUB_USERNAME=zgod
  #   volumes:
  #     - type: bind
  #       source: /var/run/docker.sock
  #       target: /var/run/docker.sock
  #   depends_on:
  #     - mosquitto
  #   networks:
  #     - oneboard-net

volumes:
  node_red_data:
  mosquitto_data:

networks:
  oneboard-net:
    name: oneboard-net
    driver: bridge